import { BookmakerCapability } from '../types/index.ts';

export const REGISTERED_BOOKMAKERS: BookmakerCapability[] = [
  {
    id: 'sportybet',
    name: 'SportyBet',
    country: 'Nigeria / Ghana / Kenya',
    logoColor: '#E61E2A',
    currency: 'NGN',
    supportedMarkets: [
      '1X2',
      'Over/Under Goals',
      'Both Teams to Score (GG/NG)',
      'Double Chance',
      'Draw No Bet (DNB)',
      'Handicap',
      'Corners O/U',
      'Clean Sheet',
    ],
    supportsCodeParsing: true,
    supportsCodeGeneration: false, // Honest status: API requires bookmaker B2B partnership
    supportsValidation: true,
    supportsConversion: true,
    integrationStatus: 'not_configured',
    bookingCodePattern: '^[A-Z0-9]{6,8}$',
    notes: 'Common booking code format: alphanumeric 6-8 chars (e.g., BC74A29). Live generator not configured.',
  },
  {
    id: 'bet9ja',
    name: 'Bet9ja',
    country: 'Nigeria',
    logoColor: '#00843D',
    currency: 'NGN',
    supportedMarkets: [
      '1X2',
      'O/U Goals',
      'GG/NG',
      '1X2 & Over 1.5',
      'DC (Double Chance)',
      'DNB',
      'Multi-Goal',
      'HT/FT',
    ],
    supportsCodeParsing: true,
    supportsCodeGeneration: false,
    supportsValidation: true,
    supportsConversion: true,
    integrationStatus: 'not_configured',
    bookingCodePattern: '^[A-Z0-9]{7,9}$',
    notes: 'Common booking code format: 7-9 alphanumeric characters. Direct API generation not configured.',
  },
  {
    id: '1xbet',
    name: '1xBet',
    country: 'International / Africa',
    logoColor: '#1A568C',
    currency: 'NGN',
    supportedMarkets: [
      '1X2',
      'Total Over/Under',
      'Both to Score',
      'Asian Handicap',
      'European Handicap',
      'Double Chance',
      'Individual Total',
    ],
    supportsCodeParsing: true,
    supportsCodeGeneration: false,
    supportsValidation: true,
    supportsConversion: true,
    integrationStatus: 'not_configured',
    bookingCodePattern: '^[A-Z0-9]{5,7}$',
    notes: 'Booking code format: 5-7 chars. Direct bookmaker API not configured.',
  },
  {
    id: 'betking',
    name: 'BetKing',
    country: 'Nigeria / Kenya / Ethiopia',
    logoColor: '#F5B942',
    currency: 'NGN',
    supportedMarkets: [
      '1X2',
      'Over/Under',
      'GG/NG',
      'Double Chance',
      'DNB',
      'First Half 1X2',
      'Correct Score',
    ],
    supportsCodeParsing: true,
    supportsCodeGeneration: false,
    supportsValidation: true,
    supportsConversion: true,
    integrationStatus: 'not_configured',
    bookingCodePattern: '^[A-Z0-9]{5,8}$',
    notes: 'Booking code format: 5-8 chars. Direct bookmaker API not configured.',
  },
];

// Mapping for ticket conversions between bookmaker terminology
export const MARKET_TRANSLATION_MAP: Record<string, Record<string, string>> = {
  sportybet_to_bet9ja: {
    'Home Win': '1',
    'Away Win': '2',
    'Draw': 'X',
    'Over 2.5': 'O 2.5',
    'Under 2.5': 'U 2.5',
    'Both Teams to Score - Yes': 'GG',
    'Both Teams to Score - No': 'NG',
    'Home or Draw (1X)': '1X',
    'Away or Draw (X2)': 'X2',
    'Home or Away (12)': '12',
    'Draw No Bet - Home': 'DNB 1',
    'Draw No Bet - Away': 'DNB 2',
  },
  bet9ja_to_sportybet: {
    '1': 'Home Win',
    '2': 'Away Win',
    'X': 'Draw',
    'O 2.5': 'Over 2.5',
    'U 2.5': 'Under 2.5',
    'GG': 'Both Teams to Score - Yes',
    'NG': 'Both Teams to Score - No',
    '1X': 'Home or Draw (1X)',
    'X2': 'Away or Draw (X2)',
    '12': 'Home or Away (12)',
    'DNB 1': 'Draw No Bet - Home',
    'DNB 2': 'Draw No Bet - Away',
  },
};
