import { Ticket, RolloverTracker, ResearchResult } from '../types/index.ts';

export const DEMO_TICKETS: Ticket[] = [
  {
    id: 'demo-ticket-1',
    title: 'Weekend European Acca (8 folds)',
    bookmaker: 'SportyBet',
    bookingCode: 'BC883F2',
    status: 'SAVED',
    source: 'USER_PROVIDED',
    extractionConfidence: 0.96,
    totalOdds: 18.42,
    stake: 2000,
    potentialReturn: 36840,
    potentialProfit: 34840,
    impliedProbability: 0.0543,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    selections: [
      {
        id: 'sel-1',
        fixtureId: 'fix-1',
        homeTeam: 'Arsenal',
        awayTeam: 'Chelsea',
        competition: 'Premier League',
        kickoffTime: '2026-10-03T16:30:00Z',
        market: 'Over/Under Goals',
        selection: 'Over 1.5 Goals',
        odds: 1.28,
        confidence: 0.98,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-2',
        fixtureId: 'fix-2',
        homeTeam: 'Real Madrid',
        awayTeam: 'Sevilla',
        competition: 'La Liga',
        kickoffTime: '2026-10-03T20:00:00Z',
        market: '1X2',
        selection: 'Real Madrid Win',
        odds: 1.45,
        confidence: 0.95,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-3',
        fixtureId: 'fix-3',
        homeTeam: 'Inter Milan',
        awayTeam: 'Roma',
        competition: 'Serie A',
        kickoffTime: '2026-10-04T17:00:00Z',
        market: 'Double Chance',
        selection: 'Inter or Draw (1X)',
        odds: 1.25,
        confidence: 0.94,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-4',
        fixtureId: 'fix-4',
        homeTeam: 'Bayern Munich',
        awayTeam: 'Dortmund',
        competition: 'Bundesliga',
        kickoffTime: '2026-10-03T17:30:00Z',
        market: 'Both Teams to Score',
        selection: 'Both Teams to Score - Yes (GG)',
        odds: 1.52,
        confidence: 0.96,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-5',
        fixtureId: 'fix-5',
        homeTeam: 'PSG',
        awayTeam: 'Marseille',
        competition: 'Ligue 1',
        kickoffTime: '2026-10-04T19:45:00Z',
        market: '1X2',
        selection: 'PSG Win',
        odds: 1.42,
        confidence: 0.93,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-6',
        fixtureId: 'fix-6',
        homeTeam: 'Napoli',
        awayTeam: 'Fiorentina',
        competition: 'Serie A',
        kickoffTime: '2026-10-04T14:00:00Z',
        market: 'Over/Under Goals',
        selection: 'Over 2.5 Goals',
        odds: 1.74,
        confidence: 0.91,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-7',
        fixtureId: 'fix-7',
        homeTeam: 'Liverpool',
        awayTeam: 'Everton',
        competition: 'Premier League',
        kickoffTime: '2026-10-03T11:30:00Z',
        market: 'Draw No Bet',
        selection: 'Liverpool (DNB)',
        odds: 1.22,
        confidence: 0.97,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-8',
        fixtureId: 'fix-8',
        homeTeam: 'Barcelona',
        awayTeam: 'Athletic Bilbao',
        competition: 'La Liga',
        kickoffTime: '2026-10-04T20:00:00Z',
        market: '1X2',
        selection: 'Barcelona Win',
        odds: 1.50,
        confidence: 0.88,
        source: 'USER_PROVIDED',
        uncertainFields: ['odds: check latest line movement'],
      },
    ],
  },
  {
    id: 'demo-ticket-2',
    title: 'Tight 5-Fold Parlay',
    bookmaker: 'Bet9ja',
    bookingCode: 'B9J44910',
    status: 'SAVED',
    source: 'USER_PROVIDED',
    extractionConfidence: 0.99,
    totalOdds: 7.85,
    stake: 5000,
    potentialReturn: 39250,
    potentialProfit: 34250,
    impliedProbability: 0.1274,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    selections: [
      {
        id: 'sel-b1',
        fixtureId: 'fix-1',
        homeTeam: 'Arsenal',
        awayTeam: 'Chelsea',
        competition: 'Premier League',
        kickoffTime: '2026-10-03T16:30:00Z',
        market: 'Over/Under Goals',
        selection: 'Over 1.5 Goals',
        odds: 1.30,
        confidence: 0.98,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-b2',
        fixtureId: 'fix-2',
        homeTeam: 'Real Madrid',
        awayTeam: 'Sevilla',
        competition: 'La Liga',
        kickoffTime: '2026-10-03T20:00:00Z',
        market: '1X2',
        selection: 'Real Madrid Win',
        odds: 1.45,
        confidence: 0.96,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-b3',
        fixtureId: 'fix-4',
        homeTeam: 'Bayern Munich',
        awayTeam: 'Dortmund',
        competition: 'Bundesliga',
        kickoffTime: '2026-10-03T17:30:00Z',
        market: 'Both Teams to Score',
        selection: 'GG',
        odds: 1.55,
        confidence: 0.97,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-b4',
        fixtureId: 'fix-5',
        homeTeam: 'PSG',
        awayTeam: 'Marseille',
        competition: 'Ligue 1',
        kickoffTime: '2026-10-04T19:45:00Z',
        market: '1X2',
        selection: 'PSG Win',
        odds: 1.42,
        confidence: 0.95,
        source: 'USER_PROVIDED',
      },
      {
        id: 'sel-b5',
        fixtureId: 'fix-7',
        homeTeam: 'Liverpool',
        awayTeam: 'Everton',
        competition: 'Premier League',
        kickoffTime: '2026-10-03T11:30:00Z',
        market: '1X2',
        selection: 'Liverpool Win',
        odds: 1.89,
        confidence: 0.92,
        source: 'USER_PROVIDED',
      },
    ],
  },
];

export const DEMO_ROLLOVER: RolloverTracker = {
  id: 'demo-rollover-1',
  bookmaker: 'SportyBet',
  bonusAmount: 350000,
  currency: 'NGN',
  rolloverMultiplier: 4,
  requiredWager: 1400000,
  completedWager: 350000,
  remainingWager: 1050000,
  progressPercentage: 25,
  minOddsPerTicket: 1.50,
  minSelectionsPerTicket: 3,
  qualifyingRules: [
    'Minimum 3 selections per qualifying accumulator',
    'Minimum cumulative odds of 1.50 per ticket',
    'Bets must be settled before 30-day bonus expiration',
    'System bets and cashed-out wagers do not count towards wagering requirement',
  ],
  startDate: '2026-09-15T00:00:00Z',
  expiryDate: '2026-10-15T23:59:59Z',
  status: 'ACTIVE',
  updatedAt: new Date().toISOString(),
};

export const DEMO_RESEARCH_FIXTURES: Record<string, ResearchResult> = {
  'fix-1': {
    fixtureId: 'fix-1',
    homeTeam: 'Arsenal',
    awayTeam: 'Chelsea',
    competition: 'Premier League',
    kickoffTime: '2026-10-03T16:30:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'D', 'W', 'W'],
    awayForm: ['D', 'W', 'L', 'W', 'D'],
    headToHead: {
      homeWins: 3,
      draws: 1,
      awayWins: 1,
      lastMatches: [
        { date: '2026-04-23', homeTeam: 'Arsenal', awayTeam: 'Chelsea', homeScore: 5, awayScore: 0 },
        { date: '2025-11-10', homeTeam: 'Chelsea', awayTeam: 'Arsenal', homeScore: 1, awayScore: 1 },
        { date: '2025-05-02', homeTeam: 'Arsenal', awayTeam: 'Chelsea', homeScore: 3, awayScore: 1 },
      ],
    },
    statistics: [
      { label: 'Avg Goals Scored / Match', homeValue: '2.4', awayValue: '1.6' },
      { label: 'Avg Goals Conceded', homeValue: '0.8', awayValue: '1.4' },
      { label: 'Clean Sheets (Last 10)', homeValue: '6', awayValue: '3' },
      { label: 'Both Teams Scored %', homeValue: '45%', awayValue: '65%' },
      { label: 'Over 1.5 Goals Rate', homeValue: '85%', awayValue: '80%' },
    ],
    standings: {
      homeRank: 2,
      awayRank: 6,
      homePoints: 16,
      awayPoints: 11,
    },
    injuries: [
      { team: 'home', player: 'M. Ødegaard', status: 'Questionable (Ankle knock)' },
      { team: 'away', player: 'R. James', status: 'Doubtful (Hamstring)' },
    ],
    observations: [
      'Arsenal has won 3 of the last 4 head-to-head fixtures at Emirates Stadium.',
      'Over 1.5 goals has hit in 85% of Arsenal home league matches over the last 12 months.',
      'Chelsea has conceded in each of their last 4 away outings.',
    ],
    limitations: [
      'Verified live lineup information is not confirmed until 60 minutes before kickoff.',
      'Weather conditions and referee assignments may affect card and foul stats.',
    ],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
  'fix-2': {
    fixtureId: 'fix-2',
    homeTeam: 'Real Madrid',
    awayTeam: 'Sevilla',
    competition: 'La Liga',
    kickoffTime: '2026-10-03T20:00:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'W', 'D', 'W'],
    awayForm: ['L', 'D', 'L', 'W', 'L'],
    headToHead: {
      homeWins: 4,
      draws: 1,
      awayWins: 0,
      lastMatches: [
        { date: '2026-02-25', homeTeam: 'Real Madrid', awayTeam: 'Sevilla', homeScore: 1, awayScore: 0 },
        { date: '2025-10-21', homeTeam: 'Sevilla', awayTeam: 'Real Madrid', homeScore: 1, awayScore: 1 },
      ],
    },
    statistics: [
      { label: 'Avg Goals Scored', homeValue: '2.8', awayValue: '0.9' },
      { label: 'Avg Goals Conceded', homeValue: '0.6', awayValue: '1.9' },
      { label: 'Home Win Rate', homeValue: '88%', awayValue: '20%' },
    ],
    standings: {
      homeRank: 1,
      awayRank: 14,
      homePoints: 21,
      awayPoints: 7,
    },
    injuries: [
      { team: 'home', player: 'D. Alaba', status: 'Rehabilitation' },
      { team: 'away', player: 'S. Ramos', status: 'Suspended (Card limit)' },
    ],
    observations: [
      'Real Madrid is unbeaten at Santiago Bernabéu against Sevilla across the last 15 meetings.',
      'Sevilla has scored only 3 goals in their last 5 away fixtures.',
    ],
    limitations: [
      'Midweek European rotation may affect starting eleven minutes.',
    ],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
  'fix-3': {
    fixtureId: 'fix-3',
    homeTeam: 'Bayern Munich',
    awayTeam: 'Borussia Dortmund',
    competition: 'Bundesliga',
    kickoffTime: '2026-10-03T17:30:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'W', 'W', 'D'],
    awayForm: ['W', 'D', 'W', 'L', 'W'],
    headToHead: {
      homeWins: 4,
      draws: 1,
      awayWins: 0,
      lastMatches: [
        { date: '2026-03-30', homeTeam: 'Bayern Munich', awayTeam: 'Dortmund', homeScore: 3, awayScore: 1 },
        { date: '2025-11-04', homeTeam: 'Dortmund', awayTeam: 'Bayern Munich', homeScore: 2, awayScore: 2 },
      ],
    },
    statistics: [
      { label: 'Avg Goals Scored', homeValue: '3.1', awayValue: '2.2' },
      { label: 'Both Teams Scored Rate', homeValue: '70%', awayValue: '80%' },
      { label: 'Over 2.5 Goals Rate', homeValue: '85%', awayValue: '75%' },
    ],
    standings: {
      homeRank: 1,
      awayRank: 3,
      homePoints: 19,
      awayPoints: 14,
    },
    observations: [
      'Both teams have scored in 7 of the last 8 Der Klassiker meetings.',
      'Bayern scores an average of 3.1 goals at Allianz Arena.',
    ],
    limitations: ['High-variance derby with elevated card likelihood.'],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
  'fix-4': {
    fixtureId: 'fix-4',
    homeTeam: 'Inter Milan',
    awayTeam: 'AS Roma',
    competition: 'Serie A',
    kickoffTime: '2026-10-04T17:00:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'D', 'W', 'W'],
    awayForm: ['D', 'L', 'W', 'D', 'W'],
    headToHead: {
      homeWins: 3,
      draws: 2,
      awayWins: 0,
      lastMatches: [
        { date: '2026-02-10', homeTeam: 'AS Roma', awayTeam: 'Inter Milan', homeScore: 2, awayScore: 4 },
        { date: '2025-10-29', homeTeam: 'Inter Milan', awayTeam: 'AS Roma', homeScore: 1, awayScore: 0 },
      ],
    },
    statistics: [
      { label: 'Avg Goals Conceded', homeValue: '0.7', awayValue: '1.3' },
      { label: 'Clean Sheet Rate', homeValue: '55%', awayValue: '30%' },
      { label: 'Double Chance (1X) Rate', homeValue: '90%', awayValue: '50%' },
    ],
    standings: {
      homeRank: 2,
      awayRank: 7,
      homePoints: 17,
      awayPoints: 10,
    },
    observations: [
      'Inter is unbeaten in their last 6 head-to-head encounters with Roma.',
      'Roma has struggled defensively away against top 4 opposition.',
    ],
    limitations: ['Midweek fatigue from continental fixture.'],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
  'fix-5': {
    fixtureId: 'fix-5',
    homeTeam: 'PSG',
    awayTeam: 'Marseille',
    competition: 'Ligue 1',
    kickoffTime: '2026-10-04T19:45:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'W', 'W', 'D'],
    awayForm: ['W', 'W', 'D', 'L', 'W'],
    headToHead: {
      homeWins: 4,
      draws: 0,
      awayWins: 1,
      lastMatches: [
        { date: '2026-03-31', homeTeam: 'Marseille', awayTeam: 'PSG', homeScore: 0, awayScore: 2 },
        { date: '2025-09-24', homeTeam: 'PSG', awayTeam: 'Marseille', homeScore: 4, awayScore: 0 },
      ],
    },
    statistics: [
      { label: 'Avg Goals Scored', homeValue: '2.6', awayValue: '1.8' },
      { label: 'Home Win Rate', homeValue: '85%', awayValue: '40%' },
      { label: 'Over 1.5 Rate', homeValue: '90%', awayValue: '80%' },
    ],
    standings: {
      homeRank: 1,
      awayRank: 4,
      homePoints: 20,
      awayPoints: 13,
    },
    observations: [
      'PSG has won 4 of the last 5 Le Classique matches at Parc des Princes.',
      'Over 1.5 goals has hit in 14 of PSG\'s last 15 home league matches.',
    ],
    limitations: ['Heated rivalry can lead to low-scoring defensive stalemates.'],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
  'fix-6': {
    fixtureId: 'fix-6',
    homeTeam: 'Napoli',
    awayTeam: 'Fiorentina',
    competition: 'Serie A',
    kickoffTime: '2026-10-04T14:00:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'W', 'L', 'W'],
    awayForm: ['D', 'D', 'W', 'D', 'L'],
    headToHead: {
      homeWins: 3,
      draws: 1,
      awayWins: 1,
      lastMatches: [
        { date: '2026-05-17', homeTeam: 'Fiorentina', awayTeam: 'Napoli', homeScore: 2, awayScore: 2 },
        { date: '2025-10-08', homeTeam: 'Napoli', awayTeam: 'Fiorentina', homeScore: 1, awayScore: 3 },
      ],
    },
    statistics: [
      { label: 'Avg Total Goals', homeValue: '2.9', awayValue: '2.4' },
      { label: 'Over 1.5 Rate', homeValue: '80%', awayValue: '75%' },
    ],
    standings: {
      homeRank: 3,
      awayRank: 8,
      homePoints: 16,
      awayPoints: 9,
    },
    observations: [
      'Fiorentina has drawn 3 of their last 4 away games.',
      'Napoli is averaging 2.1 goals scored at Stadio Diego Armando Maradona.',
    ],
    limitations: ['Fiorentina tactical shifts when facing top-3 opponents.'],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
  'fix-7': {
    fixtureId: 'fix-7',
    homeTeam: 'Liverpool',
    awayTeam: 'Everton',
    competition: 'Premier League',
    kickoffTime: '2026-10-03T11:30:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'W', 'D', 'W'],
    awayForm: ['L', 'D', 'L', 'W', 'L'],
    headToHead: {
      homeWins: 4,
      draws: 1,
      awayWins: 0,
      lastMatches: [
        { date: '2026-04-24', homeTeam: 'Everton', awayTeam: 'Liverpool', homeScore: 0, awayScore: 2 },
        { date: '2025-10-21', homeTeam: 'Liverpool', awayTeam: 'Everton', homeScore: 2, awayScore: 0 },
      ],
    },
    statistics: [
      { label: 'Home Win Rate', homeValue: '82%', awayValue: '15%' },
      { label: 'Clean Sheet Rate', homeValue: '50%', awayValue: '18%' },
      { label: 'Over 1.5 Rate', homeValue: '85%', awayValue: '65%' },
    ],
    standings: {
      homeRank: 3,
      awayRank: 16,
      homePoints: 15,
      awayPoints: 5,
    },
    observations: [
      'Liverpool has kept 4 clean sheets in their last 5 Merseyside derbies at Anfield.',
      'Everton has scored only 2 away goals all season.',
    ],
    limitations: ['Early 12:30 BST kickoff can sometimes affect match tempo.'],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
  'fix-8': {
    fixtureId: 'fix-8',
    homeTeam: 'Barcelona',
    awayTeam: 'Athletic Bilbao',
    competition: 'La Liga',
    kickoffTime: '2026-10-04T20:00:00Z',
    dataSources: ['Historical Match Database (DEMO)'],
    dataFreshness: '2026-09-28 Snapshot',
    homeForm: ['W', 'W', 'W', 'W', 'W'],
    awayForm: ['W', 'D', 'L', 'W', 'D'],
    headToHead: {
      homeWins: 3,
      draws: 1,
      awayWins: 1,
      lastMatches: [
        { date: '2026-03-03', homeTeam: 'Athletic Bilbao', awayTeam: 'Barcelona', homeScore: 0, awayScore: 0 },
        { date: '2025-10-22', homeTeam: 'Barcelona', awayTeam: 'Athletic Bilbao', homeScore: 1, awayScore: 0 },
      ],
    },
    statistics: [
      { label: 'Avg Goals Scored', homeValue: '3.0', awayValue: '1.4' },
      { label: 'Possession %', homeValue: '68%', awayValue: '48%' },
      { label: 'Over 1.5 Rate', homeValue: '90%', awayValue: '70%' },
    ],
    standings: {
      homeRank: 2,
      awayRank: 5,
      homePoints: 18,
      awayPoints: 13,
    },
    observations: [
      'Barcelona has scored in all 5 home matches this season.',
      'Athletic Bilbao maintains a stubborn low block away from home.',
    ],
    limitations: ['Bilbao key winger recovery status unverified.'],
    retrievedAt: new Date().toISOString(),
    sourceStatus: 'VERIFIED',
  },
};

import { DailyRolloverChallenge } from '../types/index.ts';

export const DEFAULT_DAILY_ROLLOVER_CHALLENGE: DailyRolloverChallenge = {
  id: 'challenge-10d-5odds',
  title: '10-Day Rollover Challenge (4-5 Odds Target)',
  startingBankroll: 10000,
  currentBankroll: 10000,
  targetMultiplier: 10,
  targetAmount: 100000,
  currency: 'NGN',
  dailyTargetOddsMin: 4.0,
  dailyTargetOddsMax: 5.0,
  totalDays: 10,
  currentDay: 1,
  status: 'ACTIVE',
  createdAt: '2026-09-29T00:00:00Z',
  updatedAt: new Date().toISOString(),
  days: [
    {
      dayNumber: 1,
      date: '2026-09-29',
      targetOdds: '4.00 - 5.00',
      status: 'READY',
      stake: 10000,
      potentialReturn: 43200,
      notes: 'Day 1 slip candidate generated with 4 selections and High data quality.',
    },
    { dayNumber: 2, date: '2026-09-30', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 3, date: '2026-10-01', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 4, date: '2026-10-02', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 5, date: '2026-10-03', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 6, date: '2026-10-04', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 7, date: '2026-10-05', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 8, date: '2026-10-06', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 9, date: '2026-10-07', targetOdds: '4.00 - 5.00', status: 'PENDING' },
    { dayNumber: 10, date: '2026-10-08', targetOdds: '4.00 - 5.00', status: 'PENDING' },
  ],
};
